### ISSUE TITLE
nrepl refactor support?

### ISSUE THREAD

**Issue by rbuchmann** [JonyEpsilon/lein-gorilla#6]
Hi,

I use gorilla and and cider, which used to work very well, albeit with some dependency difficulties that could be resolved with exclusions. However, I can not get refactor-nrepl to work. I tried putting it in different places, even cloning the gorilla repos, adding an explicit dependency and lein installing the patched versions, but it still seems to ignore it, so every time I start cider, I get a complaint that refactor-nrepl isn't active. I could live with that, but in some combinations of lein gorilla, gorilla repl, cider, tools.nrepl something really appears to break, and things outside of the functionality of refactor stop working, like overall evaluating cells in a worksheet. Do you have any advice how to deal with that?

Should I just use git repos for cider and the clj-refactor.el and force them to stable versions?

**Comment by JonyEpsilon** [comment]
I've not used refactor-nrepl, so I'm not sure I can give much useful help ... But, from a quick glance at the refactor-nrepl code, it looks as though it works by modifying the Leiningen project structure to insert some nREPL middleware. This will not work with Gorilla because currently it starts its own nREPL server, without using Leiningen, and inserts its own rendering middleware. The reason Gorilla works with CIDER is because when Gorilla starts the nREPL server it also includes the CIDER middleware (both for compatibility, and because Gorilla uses it for auto-completion and docs).

I'm not sure - if what I say above is true - what the best way to fix this is. One way would be to expand the 'CIDER workaround' and also include the refactor middleware. But I'm somewhat reluctant to go down this road, as it will bring in more dependencies that the user of Gorilla might not want (I notice that CIDER has started using mranderson to get around this problem to some extent).

Another approach would be to stop using middleware to execute Gorilla's rendering code. It could be done with source-rewriting, which might not be that bad as we only really ever call one function. I'm not sure how dependencies for the Gorilla renderer (which are currently non-existent) could be handled with this option though.

The root cause is that there's no easy way for multiple tools to specify their middleware and dependency requirements to nREPL. nREPL has a system for an individual tool to insert extra middleware at server startup time, but there's no way that I know of to coordinate this between multiple tools, or modify the middleware at runtime. I don't really have any good suggestions as to how to solve this either - not least, because the problem of tools resolving and inserting their dependencies is going to be nasty! Let me cc in @bbatsov and @cemerick in case they have any views on the wider "multiple tools with middleware" discussion.

**Comment by bbatsov** [comment]
> I'm not sure - if what I say above is true - what the best way to fix this is. One way would be to expand the 'CIDER workaround' and also include the refactor middleware. But I'm somewhat reluctant to go down this road, as it will bring in more dependencies that the user of Gorilla might not want (I notice that CIDER has started using mranderson to get around this problem to some extent).

`nrepl-refactor` uses the same approach, so I wouldn't worry about the deps.

**Comment by cemerick** [comment]
I don't know enough about what gorilla does and how it interacts with CIDER to offer any tangible assistance.

More generally though: it sounds like the objective is to allow multiple tools to contribute behaviour to a single nREPL endpoint, without coordination between those tools, and maybe even in a dynamic way at runtime. That simply isn't going to happen, without a pretty fundamental rearchitecting of how the middleware mechanisms work. We're really just talking about the composition of functions via closures here. There are ways to more loosely accrue message-handling behaviour, but such things would need different names, and you likely wouldn't be able to drop existing middleware into such a stack. That's not to say that you couldn't or shouldn't build such a thing, or that it couldn't be used to handle nREPL messages instead of the existing middleware stack approach, if there are use cases that really can't be addressed with the tools we have already.

**Comment by rbuchmann** [comment]
Hm, thanks for the input everyone, guess I am closing this for now until a better solution pops up. If nrepl-refactor gets merged into cider-nrepl, the problems impact will be reduced anyway.
